server:
  port: 8006

spring:
  application:
    name: cloud-provider-payment
  cloud:
    consul:
      host: 10.45.24.171
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true
